-- AlterTable
ALTER TABLE `notification` MODIFY `type` ENUM('GENERAL', 'WALLET', 'ENROLLMENT', 'APPLICATION_STATUS', 'COURSE_STATUS', 'NEW_RATING', 'ADMIN', 'LESSON_DISCUSSION') NOT NULL DEFAULT 'GENERAL';
