import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import AppContextProvider from "@/context/AppContext";
import { Toaster } from "sonner";
import { GoogleOAuthProvider } from "@react-oauth/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppContextProvider>
          <GoogleOAuthProvider
            clientId={process.env.NEXT_PUBLIC_AUTH_CLIENT_ID ?? ""}
          >
            <div
              className="
            min-h-screen 
            mx-auto 
            my-2.5 md:my-4 lg:my-8
            px-4 sm:px-6 md:px-8 
            max-w-full sm:max-w-3xl md:max-w-5xl lg:max-w-7xl xl:max-w-[1600px] 2xl:max-w-[1920px]
          "
            >
              {children}
              <Toaster position="top-right" />
              <Footer />
            </div>
          </GoogleOAuthProvider>
        </AppContextProvider>
      </body>
    </html>
  );
}
